<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-StudentRegistry-b7ea4f97-9d14-4bb2-814c-91fd5b5acbee</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.10" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="RegistroDeEstudantes.Tests/**/*.cs" />
        <EmbeddedResource Remove="RegistroDeEstudantes.Tests/**/*.resx" />
        <None Remove="RegistroDeEstudantes.Tests/**" />
    </ItemGroup>


</Project>

